# Generated by Django 6.0.3 on 2026-04-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_prefix", models.CharField(blank=True, max_length=10)),
                ("amount", models.PositiveIntegerField(help_text="Fee in cents")),
                ("currency", models.CharField(default="aud", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100, help_text="Lower means chosen first"
                    ),
                ),
            ],
        ),
    ]
